# Generated by Django 3.2 on 2021-06-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_img_id', to='main.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_img_id', to='main.image')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_id', to='main.objects')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lbl_img_id', to='main.image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_id', to='main.labels')),
            ],
        ),
    ]
