# Generated by Django 3.2 on 2021-06-09 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabels',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lbl_img_id', to='main.image'),
        ),
        migrations.AlterField(
            model_name='imagelabels',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='label_id', to='main.labels'),
        ),
        migrations.AlterField(
            model_name='imageobjects',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='obj_img_id', to='main.image'),
        ),
        migrations.AlterField(
            model_name='imageobjects',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='obj_id', to='main.objects'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_img_id', to='main.image'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
